# vim: ft=dosini
#
# aerc TokyoNight styleset
# set styleset-name=tokyonight-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#a8aecb
border.bg=#ffffff

title.fg=#cccccc
title.bg=#2e7de9
title.bold=true

header.fg=#f52a65
#header.bg=#ffffff
header.bold=true

tab.fg=#a8aecb
tab.bg=#ebeff9
tab.selected.fg=#cccccc
tab.selected.bg=#2e7de9

statusline_default.fg=#3760bf
statusline_default.bg=#ebeff9
statusline_error.fg=#c64343
statusline_success.fg=#387068

*error.bold=true
*error.fg=#c64343
*warning.fg=#8c6c3e
*success.fg=#387068

dirlist_*.bg=#ffffff
dirlist_*.fg=#3760bf
dirlist_*.selected.bg=#c9d3f1
dirlist_*.selected.fg=#3760bf

msglist_*.bg=#ffffff
msglist_*.fg=#3760bf
msglist_*.selected.bg=#c9d3f1
#msglist_*.selected.fg=#3760bf
msglist_unread.bold=true
msglist_unread.fg=#2e7de9
msglist_marked.fg=#b15c00
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#c4c8da
msglist_pill.bg=#a8aecb
msglist_pill.reverse=false

part_*.fg=#3760bf
part_*.bg=#ebeff9
part_*.selected.fg=#3760bf
part_*.selected.bg=#a8aecb

completion_default.bg=#ebeff9
completion_default.fg=#3760bf
completion_default.selected.bg=#a8aecb
completion_default.selected.fg=#3760bf
completion_gutter.bg=#c4c8da
completion_pill.bg=#a8aecb
completion_pill.reverse=false

spinner.bg=#ffffff
spinner.fg=#3760bf

selector_focused.bold=false
selector_focused.bg=#c9d3f1
selector_focused.fg=#3760bf
selector_chooser.bold=false
selector_chooser.bg=#c9d3f1
selector_chooser.fg=#3760bf
default.selected.bold=false
default.selected.fg=#3760bf
default.selected.bg=#c9d3f1

[viewer]
url.underline=true
url.fg=#68709a
header.fg=#7847bd
signature.fg=#9854f1
diff_add.fg=#e1eff1
diff_del.fg=#f6e3e3
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#8c6c3e
quote_2.fg=#587539
quote_3.fg=#118c74
quote_3.dim=true
quote_4.fg=#2e7de9
quote_4.dim=true
quote_x.fg=#848cb5
quote_x.dim=true

